version: "3"
services:
  scrollerdb:
    build:
      context: data/
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_USER: test
      MYSQL_PASSWORD: pass
      MYSQL_DATABASE: Scroller_db
    volumes:
      - ./data-volume:/var/lib/mysql
    networks:
      - platform
    ports:
      - 3307:3306
  scroller:
    build: ./
    expose:
      - 80
    networks:
      - platform
networks:
  platform:
    external:
      name: websocket-scroller
